---
 - hosts: all
   gather_facts: no
   
   tasks:
   - name: Update all packages to the latest version
     apt:
       upgrade: dist

   - name: Install required system packages
     apt: name={{ item }} state=latest update_cache=yes
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

   - name: Add Apt key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   tasks:
   - name: Update all packages to the latest version
     apt:
       upgrade: dist

   - name: Update apt and install docker-ce
     apt: 
       update_cache: yes
       name: docker-ce
       state: latest
   
   - name: Update apt and install docker-ce-cli
     apt: 
       name: docker-ce-cli
       state: latest
   
   - name: Update apt and install containerd.io
     apt: 
       name: containerd.io
       state: latest

   - name: Install Docker Module for Python
     pip:
       name: docker
   





