---
 - hosts: all
   gather_facts: no
   
   tasks:
   - name: Update all packages to the latest version
     apt:
       upgrade: dist

   - name: Checking apt-transport-https
     apt: 
       name: apt-transport-https
       state: present
   
   - name: Checking ca-certificates
     apt: 
       name: ca-certificates
       state: present
   
   - name: Checking curl 
     apt: 
       name: curl 
       state: present

   - name: Checking gnupg-agent 
     apt: 
       name: gnupg-agent 
       state: present

   - name: Checking software-properties-common
     apt: 
       name: software-properties-common 
       state: present

   - name: Add Apt key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   tasks:
   - name: Update all packages to the latest version
     apt:
       upgrade: dist

   - name: Update apt and install docker-ce
     apt: 
       update_cache: yes
       name: docker-ce
       state: latest
   
   - name: Update apt and install docker-ce-cli
     apt: 
       name: docker-ce-cli
       state: latest
   
   - name: Update apt and install containerd.io
     apt: 
       name: containerd.io
       state: latest

   - name: Install Docker Module for Python
     pip:
       name: docker
   





